installationMethod: openshift-helm

collector:
  enabled: true
  image:
    repository: registry.connect.redhat.com/wavefronthq/wavefront-kubernetes-collector
    tag: 1.10.0
    pullPolicy: IfNotPresent
  discovery:
    # Exclude resources from annotation-based discovery
    annotationExcludes:
    - resourceType: "service"
      # namespaces to filter resources by. Provided as a list of glob pattern strings.
      namespaces:
      - "openshift-*"
proxy:
  enabled: true
  image:
    repository: registry.connect.redhat.com/wavefronthq/proxy
    tag: 10.14.1
    pullPolicy: IfNotPresent

openshift:
  enabled: true

testCollectorImage: registry.connect.redhat.com/seldonio/kubectl
