{{- if .Values.proxy.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name : {{ template "wavefront.fullname" . }}
    helm.sh/chart: {{ template "wavefront.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io.instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: proxy
  name: {{ template "wavefront.proxy.fullname" . }}
spec:
  replicas: {{ .Values.proxy.replicas }}
  selector:
    matchLabels:
      app.kubernetes.io/name : {{ template "wavefront.fullname" .}}
      app.kubernetes.io/component: proxy
  template:
    metadata:
      labels:
        app.kubernetes.io/name : {{ template "wavefront.fullname" .}}
        app.kubernetes.io/component: proxy
    spec:
      {{- if .Values.imagePullSecrets }}
      imagePullSecrets: {{ toYaml .Values.imagePullSecrets | nindent 6 }}
      {{- end }}
      containers:
      - name: wavefront-proxy
        image: {{ .Values.proxy.image.repository }}:{{ .Values.proxy.image.tag }}
        imagePullPolicy: {{ .Values.proxy.image.pullPolicy }}
        env:
        - name: WAVEFRONT_URL
          value: {{ .Values.wavefront.url }}/api
        {{- if .Values.wavefront.tokenFromSecret }}
        - name: WAVEFRONT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ .Values.wavefront.tokenFromSecret }}
              key: api-token
        {{- else }}
        - name: WAVEFRONT_TOKEN
          valueFrom:
            secretKeyRef:
              name: {{ template "wavefront.fullname" . }}
              key: api-token
        {{- end }}
        - name: WAVEFRONT_PROXY_ARGS
          value: {{ .Values.proxy.args }}
          {{- if .Values.proxy.tracePort }} --traceListenerPorts {{ .Values.proxy.tracePort }}{{- end -}}
          {{- if .Values.proxy.jaegerPort }} --traceJaegerListenerPorts {{ .Values.proxy.jaegerPort }}{{- end -}}
          {{- if .Values.proxy.traceJaegerHttpListenerPort }} --traceJaegerHttpListenerPorts {{ .Values.proxy.traceJaegerHttpListenerPort }}{{- end -}}
          {{- if .Values.proxy.traceJaegerGrpcListenerPort }} --traceJaegerGrpcListenerPorts {{ .Values.proxy.traceJaegerGrpcListenerPort }}{{- end -}}
          {{- if .Values.proxy.zipkinPort }} --traceZipkinListenerPorts {{ .Values.proxy.zipkinPort }}{{- end -}}
          {{- if .Values.proxy.traceSamplingRate }} --traceSamplingRate {{ .Values.proxy.traceSamplingRate }}{{- end -}}
          {{- if .Values.proxy.traceSamplingDuration }} --traceSamplingDuration {{ .Values.proxy.traceSamplingDuration }}{{- end -}}
          {{- if .Values.proxy.traceJaegerApplicationName }} --traceJaegerApplicationName {{ .Values.proxy.traceJaegerApplicationName }}{{- end -}}
          {{- if .Values.proxy.traceZipkinApplicationName }} --traceZipkinApplicationName {{ .Values.proxy.traceZipkinApplicationName }}{{- end -}}
          {{- if .Values.proxy.histogramPort }} --histogramDistListenerPorts {{ .Values.proxy.histogramPort }}{{- end -}}
          {{- if .Values.proxy.histogramMinutePort }} --histogramMinuteListenerPorts {{ .Values.proxy.histogramMinutePort }}{{- end -}}
          {{- if .Values.proxy.histogramHourPort }} --histogramHourListenerPorts {{ .Values.proxy.histogramHourPort }}{{- end -}}
          {{- if .Values.proxy.histogramDayPort }} --histogramDayListenerPorts {{ .Values.proxy.histogramDayPort }}{{- end -}}
          {{- if .Values.proxy.deltaCounterPort }} --deltaCountersAggregationListenerPorts {{ .Values.proxy.deltaCounterPort }}{{- end -}}
          {{- if .Values.proxy.preprocessor }} --preprocessorConfigFile /etc/wavefront/wavefront-proxy/preprocessor/rules.yaml{{- end -}}
          {{- if .Values.proxy.httpProxyHost }} --proxyHost {{ .Values.proxy.httpProxyHost }}{{- end -}}
          {{- if .Values.proxy.httpProxyPort }} --proxyPort {{ .Values.proxy.httpProxyPort }}{{- end -}}
          {{- if .Values.proxy.httpProxyUser }} --proxyUser {{ .Values.proxy.httpProxyUser }}{{- end -}}
          {{- if .Values.proxy.httpProxyPassword }} --proxyPassword {{ .Values.proxy.httpProxyPassword }}{{- end -}}
        {{- if .Values.proxy.heap }}
        - name: JAVA_HEAP_USAGE
          value: {{ .Values.proxy.heap | quote }}
        {{- end }}
        ports:
        - containerPort: {{ .Values.proxy.port }}
          protocol: TCP
        {{- if .Values.proxy.tracePort }}
        - containerPort: {{ .Values.proxy.tracePort }}
          protocol: TCP
        {{- end }}
        {{- if .Values.proxy.jaegerPort }}
        - containerPort: {{ .Values.proxy.jaegerPort }}
          protocol: TCP
        {{- end }}
        {{- if .Values.proxy.traceJaegerHttpListenerPort }}
        - containerPort: {{ .Values.proxy.traceJaegerHttpListenerPort }}
          protocol: TCP
        {{- end }}
        {{- if .Values.proxy.traceJaegerGrpcListenerPort }}
        - containerPort: {{ .Values.proxy.traceJaegerGrpcListenerPort }}
          protocol: TCP
        {{- end }}
        {{- if .Values.proxy.zipkinPort }}
        - containerPort: {{ .Values.proxy.zipkinPort }}
          protocol: TCP
        {{- end }}
        {{- if .Values.proxy.histogramPort }}
        - containerPort: {{ .Values.proxy.histogramPort }}
          protocol: TCP
        {{- end }}
        {{- if .Values.proxy.histogramMinutePort }}
        - containerPort: {{ .Values.proxy.histogramMinutePort }}
          protocol: TCP
        {{- end }}
        {{- if .Values.proxy.histogramHourPort }}
        - containerPort: {{ .Values.proxy.histogramHourPort }}
          protocol: TCP
        {{- end }}
        {{- if .Values.proxy.histogramDayPort }}
        - containerPort: {{ .Values.proxy.histogramDayPort }}
          protocol: TCP
        {{- end }}
        {{- if .Values.proxy.deltaCounterPort }}
        - containerPort: {{ .Values.proxy.deltaCounterPort }}
          protocol: TCP
        {{- end }}
        resources:
{{ toYaml .Values.proxy.resources | trim | indent 10 }}
        securityContext:
          privileged: false
        volumeMounts:
        {{- if .Values.proxy.preprocessor }}
        - name: preprocessor
          mountPath: /etc/wavefront/wavefront-proxy/preprocessor
        {{- end }}
        {{- if .Values.proxy.useHttpProxyCAcert }}
        - name: http-proxy-ca
          mountPath: /tmp/ca
        {{- end }}
    {{- if .Values.proxy.priorityClassName }}
      priorityClassName: {{ .Values.proxy.priorityClassName }}
    {{- end }}
{{- if .Values.proxy.tolerations }}
      tolerations:
{{ toYaml .Values.proxy.tolerations | indent 6 }}
    {{- end }}
      volumes:
      {{- if .Values.proxy.preprocessor }}
      - name: preprocessor
        configMap:
          name: {{ template "wavefront.proxy.fullname" . }}-preprocessor
      {{- end }}
      {{- if .Values.proxy.useHttpProxyCAcert }}
      - name: http-proxy-ca
        secret:
          secretName: http-proxy-secret
          items:
            - key: tls-root-ca-bundle
              path: ca.pem
      {{- end }}
{{- end }}
