{{- if .Values.proxy.logsingestion }}
apiVersion: v1
kind: ConfigMap
metadata:
  labels:
    app.kubernetes.io/name : {{ template "wavefront.fullname" . }}
    helm.sh/chart: {{ template "wavefront.chart" . }}
    app.kubernetes.io/managed-by: {{ .Release.Service | quote }}
    app.kubernetes.io.instance: {{ .Release.Name | quote }}
    app.kubernetes.io/component: proxy
  name: {{ template "wavefront.proxy.fullname" . }}-logsingestion
data:
{{ tpl (toYaml .Values.proxy.logsingestion) . | indent 2 }}
{{- end }}
