apiVersion: v2
name: wavefront
description: Wavefront Collector for Kubernetes
appVersion: 1.11.0
version: 1.11.0
keywords:
- metric
- monitoring
- observability
- alerting
home: https://www.wavefront.com
sources:
- https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes
- https://github.com/wavefrontHQ/wavefront-proxy
maintainers:
  - name: akodali18
    email: akodali@vmware.com
  - name: johncornish
    email: jcornish@vmware.com
  - name: josephgee
    email: jgee@vmware.com
  - name: helen-shao
    email: shaoh@vmware.com
  - name: mceldeen
    email: matthewco@vmware.com
  - name: mmichael
    email: mamichael@vmware.com
  - name: priyaselvaganesan
    email: pselvaganesa@vmware.com
dependencies:
  - name: kube-state-metrics
    version: ^4.7.0
    repository: https://prometheus-community.github.io/helm-charts
    condition: kubeStateMetrics.enabled
