apiVersion: v1
name: wavefront
description: Wavefront Collector for Kubernetes
appVersion: 1.3.6
version: 1.3.12
keywords:
- metric
- monitoring
- observability
- alerting
home: https://www.wavefront.com
sources:
- https://github.com/wavefrontHQ/wavefront-collector-for-kubernetes
- https://github.com/wavefrontHQ/wavefront-proxy
maintainers:
- name: josephgee
  email: jgee@vmware.com
- name: JSchuenke
  email: jschuenke@vmware.com
- name: mmichael
  email: mamichael@vmware.com
