apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1beta1.external.metrics.k8s.io
  labels:
{{ include "wavefront-hpa-adapter.labels" . | indent 4 }}
spec:
  service:
    name: {{ include "wavefront-hpa-adapter.fullname" . }}
    namespace: {{ .Release.Namespace }}
  group: external.metrics.k8s.io
  version: v1beta1
  insecureSkipTLSVerify: true
  groupPriorityMinimum: 100
  versionPriority: 100
